//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsmsSchemaFolders.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SsmsSchemaFolders.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string PropertyCategorySchemaFolderOptionsActive {
            get {
                return ResourceManager.GetString("PropertyCategorySchemaFolderOptionsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Display Options.
        /// </summary>
        internal static string PropertyCategorySchemaFolderOptionsFolderDisplayOptions {
            get {
                return ResourceManager.GetString("PropertyCategorySchemaFolderOptionsFolderDisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Level 1.
        /// </summary>
        internal static string PropertyCategorySchemaFolderOptionsFolderLevel1 {
            get {
                return ResourceManager.GetString("PropertyCategorySchemaFolderOptionsFolderLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Level 2.
        /// </summary>
        internal static string PropertyCategorySchemaFolderOptionsFolderLevel2 {
            get {
                return ResourceManager.GetString("PropertyCategorySchemaFolderOptionsFolderLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Display Options.
        /// </summary>
        internal static string PropertyCategorySchemaFolderOptionsObjectDisplayOptions {
            get {
                return ResourceManager.GetString("PropertyCategorySchemaFolderOptionsObjectDisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string PropertyCategorySchemaFolderOptionsPerformance {
            get {
                return ResourceManager.GetString("PropertyCategorySchemaFolderOptionsPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a dot after the schema name on the folder label..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsAppendDot {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsAppendDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the right click and connection properties of the parent node to the schema folder node..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsCloneParentNode {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsCloneParentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group sql objects in Object Explorer (tables, views, etc.) into schema folders..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsEnabled {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold the modifier keys down to do the opposite of the Enabled setting. The letter key (or None) in the setting is not used but is required by the settings editor. To change a folder that has already been opened, right-click the folder and select refresh while holding the keys..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsEnabledModifierKeys {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsEnabledModifierKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of sorting to use to create the folders..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsLevel1FolderType {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsLevel1FolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort nodes into folders only when it contains at least this many nodes..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsLevel1MinNodeCount {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsLevel1MinNodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of sorting to use to create the folders..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsLevel2FolderType {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsLevel2FolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort nodes into folders only when it contains at least this many nodes..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsLevel2MinNodeCount {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsLevel2MinNodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min node count required before using faster but inaccurate method to get schema. Zero = disabled..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsQuickSchema {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsQuickSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the schema name from the object node..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsRenameNode {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsRenameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds. Increasing will update faster but be more unresponsive..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsUnresponsiveTimeout {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsUnresponsiveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min node count required before using faster method but will be unresponsive while updating. Zero = disabled..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsUseClear {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsUseClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the icon of the last child node as the folder icon. If false then use the parent node (i.e. folder) icon..
        /// </summary>
        internal static string PropertyDescriptionSchemaFolderOptionsUseObjectIcon {
            get {
                return ResourceManager.GetString("PropertyDescriptionSchemaFolderOptionsUseObjectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Dot.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsAppendDot {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsAppendDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Parent Node.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsCloneParentNode {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsCloneParentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsEnabled {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Keys.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsEnabledModifierKeys {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsEnabledModifierKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Type.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsLevel1FolderType {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsLevel1FolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Node Count.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsLevel1MinNodeCount {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsLevel1MinNodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Type.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsLevel2FolderType {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsLevel2FolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Node Count.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsLevel2MinNodeCount {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsLevel2MinNodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick schema from node text.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsQuickSchema {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsQuickSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Node.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsRenameNode {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsRenameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresponsive timeout.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsUnresponsiveTimeout {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsUnresponsiveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Nodes.Clear.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsUseClear {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsUseClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Object Icon.
        /// </summary>
        internal static string PropertyDisplayNameSchemaFolderOptionsUseObjectIcon {
            get {
                return ResourceManager.GetString("PropertyDisplayNameSchemaFolderOptionsUseObjectIcon", resourceCulture);
            }
        }
    }
}
